# Generated by Django 4.1.3 on 2022-12-08 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0002_post_like'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='like',
            new_name='likes',
        ),
    ]
